services:
  - type: web
      name: trading-bot
          env: python
              buildCommand: |
                    pip install -r requirements.txt
                        startCommand: bash start.sh